spring.application.name=SpringbootCrudApplication

spring.datasource.url=jdbc:mysql://localhost:3306/STUDENT_CRUD_DB
spring.datasource.username=root
spring.datasource.password=Shiv@123

spring.jpa.hibernate.ddl-auto=update


